[phases.setup]
nixPkgs = ["python312", "gcc", "chromium", "nodejs_23"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install uv==$NIXPACKS_UV_VERSION",
  "uv sync --frozen --no-dev --no-editable",
  "cd frontend && npm install --include=optional",
  "cd frontend && npm run build",
]

[variables]
CHROME_BIN = "chromium"
CHROMIUM_PATH = "chromium"

[start]
cmd = "/opt/venv/bin/python main.py"
